### ISSUE TITLE
Proguard config for Ezetap

### ISSUE THREAD

**Issue by visareshwar** [ezetap/client-sdk-android#4]
Hi,
What is pro-guard config for this lib. I am getting error on building Like Warning:com.eze.api.EzeAPIPlugin: can't find superclass or interface org.apache.cordova.CordovaPlugin

Error:Execution failed for task ':app:transformClassesAndResourcesWithProguardForProductionRelease'.
> Job failed, see logs for details

**Comment by ShashankEzetap** [comment]
Hi Vishu,

Please add the below rules in proguard-rules.pro file & let me know if it works

# Apache legacy
-keep class org.apache.http.** { *; }
-keep class org.apache.commons.codec.** { *; }
-keep class org.apache.commons.logging.** { *; }
-keep class android.net.compatibility.** { *; }
-keep class android.net.http.** { *; }
-keep class com.android.internal.http.multipart.** { *; }
-dontwarn org.apache.http.**
-dontwarn android.webkit.**

#Ezetap SDK
-keep class android.support.v7.widget.SearchView { *; }
-dontwarn com.ezetap.**
-dontwarn com.eze.**

**Comment by kinishah26** [comment]
Tried using above mentioned solution but getting this error : 

Error:warning: Supported source version 'RELEASE_7' from annotation processor 'android.arch.lifecycle.LifecycleProcessor' less than -source '1.8'
warning: Supported source version 'RELEASE_7' from annotation processor 'android.arch.persistence.room.RoomProcessor' less than -source '1.8'
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
2 warnings
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:transformClassesAndResourcesWithProguardForRelease'.
> Job failed, see logs for details

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 4m 51s
