### ISSUE TITLE
Cannot aassign a termianl to Ezetap device

### ISSUE THREAD

**Issue by Sharonsudhan** [ezetap/client-sdk-android#5]
I am getting below error while trying to initialize device "Cannot assign a Terminal to Ezetap Device ".
I have put prepare device as true in request.

jsonRequest.put("prepareDevice", "true");

Thanks
Sharon

**Comment by Sharonsudhan** [comment]
Added an empty terminal and issue got fixed

**Comment by Sharonsudhan** [comment]
Added an empty terminal and issue got fixed

**Comment by Amuthakmba** [comment]
I am getting below error while trying to initialize device "Cannot assign a Terminal to Ezetap Device ".
 I have put prepare device as true in request.
 

 
 Thanks
guru prakash
